### ISSUE TITLE
Error install gulp .env

### ISSUE THREAD

**Issue by Paul75** [rfprod/ng2ns#1]
Hello,

When do : 
`gulp create-env`

I've got : 
```
[09:48:09] Using gulpfile ~/Projects/printaplus/git/printaplus/site/Ng2NS/gulpfile.js
PROCESS EXIT CODE 1
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

Thanks

**Comment by rfprod** [comment]
@Paul75 several questions:
* do you have errors with this gulp task only?
* do you have gulp installed globally?

check updated readme for info on [required global dependencies](https://github.com/rfprod/ng2ns#global-dependencies)

could not reproduce the error by now, provide more details if you still encounter it.
